// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Proba.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.Admin", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("KorisnikID")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("ID");

                    b.HasIndex("KorisnikID");

                    b.ToTable("Admini");
                });

            modelBuilder.Entity("Models.Korisnik", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DatumRodjenja")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("NVARCHAR2(25)");

                    b.Property<string>("KorisnickoIme")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("Lozinka")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("NVARCHAR2(25)");

                    b.Property<string>("TipKorisnika")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.HasKey("ID");

                    b.ToTable("Korisnici");
                });

            modelBuilder.Entity("Models.Kupac", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BrojLezaljki")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("KorisnikID")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Slika")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("Uverenje")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.HasKey("ID");

                    b.HasIndex("KorisnikID");

                    b.ToTable("Kupaci");
                });

            modelBuilder.Entity("Models.Lezaljka", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<double>("Cena")
                        .HasColumnType("BINARY_DOUBLE");

                    b.HasKey("ID");

                    b.ToTable("Lezaljke");
                });

            modelBuilder.Entity("Models.Radnik", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("RID")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Sertifikat")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("Slika")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.HasKey("ID");

                    b.HasIndex("RID");

                    b.ToTable("Radnici");
                });

            modelBuilder.Entity("Models.Rezervacije", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("KID")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("LID")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("ID");

                    b.HasIndex("KID");

                    b.HasIndex("LID");

                    b.ToTable("Rezervacije");
                });

            modelBuilder.Entity("Models.ZahtevIzdavanje", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("AID")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("KID")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.Property<string>("Tip_Karte")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.HasKey("ID");

                    b.HasIndex("AID");

                    b.HasIndex("KID");

                    b.ToTable("ZahtevIzdavanje");
                });

            modelBuilder.Entity("Models.ZahtevPosao", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("AID")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Opis")
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)");

                    b.Property<int?>("SRID")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.Property<string>("Tip_Posla")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.HasKey("ID");

                    b.HasIndex("AID");

                    b.HasIndex("SRID");

                    b.ToTable("ZahtevPosao");
                });

            modelBuilder.Entity("Models.Admin", b =>
                {
                    b.HasOne("Models.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("Models.Kupac", b =>
                {
                    b.HasOne("Models.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("Models.Radnik", b =>
                {
                    b.HasOne("Models.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("RID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("Models.Rezervacije", b =>
                {
                    b.HasOne("Models.Kupac", "Kupac")
                        .WithMany("Rezervacije")
                        .HasForeignKey("KID");

                    b.HasOne("Models.Lezaljka", "Lezaljka")
                        .WithMany("Rezervacije")
                        .HasForeignKey("LID");

                    b.Navigation("Kupac");

                    b.Navigation("Lezaljka");
                });

            modelBuilder.Entity("Models.ZahtevIzdavanje", b =>
                {
                    b.HasOne("Models.Admin", "Admin")
                        .WithMany("ZahtevIzdavanje")
                        .HasForeignKey("AID");

                    b.HasOne("Models.Kupac", "Kupac")
                        .WithMany("ZahtevIzdavanje")
                        .HasForeignKey("KID");

                    b.Navigation("Admin");

                    b.Navigation("Kupac");
                });

            modelBuilder.Entity("Models.ZahtevPosao", b =>
                {
                    b.HasOne("Models.Admin", "Admin")
                        .WithMany("ZahtevPosao")
                        .HasForeignKey("AID");

                    b.HasOne("Models.Radnik", "Radnik")
                        .WithMany("ZahtevPosao")
                        .HasForeignKey("SRID");

                    b.Navigation("Admin");

                    b.Navigation("Radnik");
                });

            modelBuilder.Entity("Models.Admin", b =>
                {
                    b.Navigation("ZahtevIzdavanje");

                    b.Navigation("ZahtevPosao");
                });

            modelBuilder.Entity("Models.Kupac", b =>
                {
                    b.Navigation("Rezervacije");

                    b.Navigation("ZahtevIzdavanje");
                });

            modelBuilder.Entity("Models.Lezaljka", b =>
                {
                    b.Navigation("Rezervacije");
                });

            modelBuilder.Entity("Models.Radnik", b =>
                {
                    b.Navigation("ZahtevPosao");
                });
#pragma warning restore 612, 618
        }
    }
}
